list_of_jobs = [
    "Job Title: Senior Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-developer-lemon-io-1093252",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior React Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-react-full-stack-developer-lemon-io-1093015",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-developer-lemon-io-1087780",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-developer-lemon-io-1069348",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack React.js Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-react-js-developer-lemon-io-901506",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack React.js Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-react-js-developer-lemon-io-852038",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior React & React Native Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-react-react-native-developer-lemon-io-801799",
    "----------------------------------------",
    "Company: VettaFI",
    "Job Title: Backend Full Stack Software Engineer",
    "Link: https://remoteok.com/remote-jobs/remote-backend-full-stack-software-engineer-vettafi-755806",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack React Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-react-developer-lemon-io-754016",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Senior Full stack React Developer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-full-stack-react-developer-lemon-io-631301",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Data Scientist & Data Engineer AI ML",
    "Link: https://remoteok.com/remote-jobs/remote-data-scientist-data-engineer-ai-ml-lemon-io-613825",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-developer-lemon-io-585314",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack React Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-react-developer-lemon-io-459455",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Python Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-python-developer-lemon-io-354496",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-developer-lemon-io-281173",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Python Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-python-developer-lemon-io-252173",
    "----------------------------------------",
    "Company: Gower Street Analytics",
    "Job Title: Senior Engineer",
    "Link: https://remoteok.com/remote-jobs/remote-senior-engineer-gower-street-analytics-228536",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-developer-lemon-io-243056",
    "----------------------------------------",
    "Company: Lemon.io",
    "Job Title: Full stack Python Developer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-python-developer-lemon-io-215412",
    "----------------------------------------",
    "Company: Avante IO",
    "Job Title: Full Stack Engineer",
    "Link: https://remoteok.com/remote-jobs/remote-full-stack-engineer-avante-io-213836",
    "----------------------------------------",
]